import * as THREE from 'three';
import { GAME,WEAPONS,OBJECTIVES } from '../config.js';
import { formatTime,clamp } from '../utils/math.js';
const emblem=`<svg viewBox="0 0 40 48" fill="none" aria-hidden="true"><path d="m20 2 15 18-15 25L5 20Z" fill="currentColor" opacity=".2"/><path d="m20 2 15 18-15 25L5 20Z" stroke="currentColor" stroke-width="1.5"/><path d="m20 2-4 18 4 25 5-25Z" fill="currentColor"/><path d="M5 20h30" stroke="currentColor"/></svg>`;
const arrow=`<svg width="20" height="20" viewBox="0 0 24 24" fill="none"><path d="M4 12h15M13 5l7 7-7 7" stroke="currentColor" stroke-width="1.8"/></svg>`;
export class UI {
  constructor(game){this.game=game;this.el=document.querySelector('#app');this.lastStage=-1;this.toastTimer=0;this.quipTimer=0;this.hitTimer=0;this.floaters=[];this.currentModal=null;this.draw();this.bind();}
  draw(){this.el.innerHTML=`
    <div class="vignette"></div><div id="damage" class="damage-overlay"></div>
    <section id="loading" class="loading screen"><div class="loading-inner"><div class="brand-gem">${emblem}</div><div class="eyebrow">A VERY QUESTIONABLE ADVENTURE</div><h1 class="load-title">CHAOS <span>LEGENDS</span></h1><p>Building a world that absolutely needs your help.</p><div class="load-track"><i id="load-fill"></i></div><div class="load-status"><span id="load-note">Preparing Whispering Valley</span><b id="load-percent">0%</b></div><p class="tip" id="load-tip">TIP · Q dashes through danger. E pushes danger away.</p></div><div class="creator">CREATED BY ${GAME.author.toUpperCase()}</div></section>
    <section id="menu" class="menu screen hidden">
      <header class="menu-header"><a class="wordmark" href="${GAME.repo}" target="_blank" rel="noopener">${emblem}<span>AZADI <b>PLAY</b></span></a><div class="build-label"><i></i> BROWSER EDITION <span>01 / WHISPERING VALLEY</span></div></header>
      <div class="menu-content"><div class="eyebrow"><span class="small-line"></span> AN ORIGINAL FANTASY SHOOTER</div><h1 class="game-title">CHAOS<br><span>LEGENDS<span class="title-dot">.</span></span></h1><p class="tagline">Big magic. Bad plans.<br><b>Absolutely no qualified heroes.</b></p><div class="menu-buttons"><button id="play" class="primary"><span>START ADVENTURE <small>Save the village… probably.</small></span>${arrow}</button><button id="continue" class="secondary" disabled>CONTINUE MISSION <span>↗</span></button></div><nav class="menu-links"><button data-modal="settings">SETTINGS</button><span>/</span><button data-modal="controls">CONTROLS</button><span>/</span><button data-modal="about">ABOUT & CREDITS</button></nav></div>
      <div class="chapter-card"><span class="chapter-index">01</span><div><div class="eyebrow">YOUR FIRST QUESTIONABLE QUEST</div><h2>Whispering Valley</h2><p>A stolen crystal. A goblin invasion.<br>A mercenary with very little self-awareness.</p></div></div>
      <footer class="menu-footer"><span>CREATED BY <b>${GAME.author.toUpperCase()}</b></span><span class="desktop-note"><span class="key small">W</span><span class="key small">A</span><span class="key small">S</span><span class="key small">D</span> + MOUSE <i></i> DESKTOP RECOMMENDED</span><a href="${GAME.repo}" target="_blank" rel="noopener">GITHUB ${arrow}</a></footer>
    </section>
    <section id="hud" class="hud hidden">
      <div class="objective-card"><div class="eyebrow"><i class="live-dot"></i> SAVE THE VILLAGE… PROBABLY <span id="objective-count">01 / 07</span></div><h2 id="objective-title">Enter the village</h2><p id="objective-detail">Follow the lanterns to the village square.</p><div class="mission-steps">${OBJECTIVES.map((_,i)=>`<i data-step="${i}"></i>`).join('')}</div></div>
      <div class="top-center"><span class="compass">W <b id="heading">N</b> E</span><div id="boss-hud" class="boss hidden"><div><b>THE GRAND GOBBLER</b><span id="boss-state">VERY LARGE EGO</span></div><div class="boss-track"><i id="boss-fill"></i></div></div></div>
      <div class="map-wrap"><div class="eyebrow">WHISPERING VALLEY <span>N ↑</span></div><canvas id="minimap" width="192" height="166"></canvas><div class="map-bottom"><span id="score">000000</span> SCORE <b id="coins">0 ◈</b></div></div>
      <div id="crosshair" class="crosshair"><i></i><i></i><i></i><i></i><b></b></div><div id="hitmarker" class="hitmarker hidden">×</div><div id="objective-marker" class="world-marker">${emblem}<span id="marker-distance">32 m</span></div>
      <div id="interaction" class="interaction hidden"><span class="key">F</span><span id="interaction-text">Open chest</span></div>
      <div class="player-card"><div class="player-name"><span class="hero-emblem">${emblem}</span><div><b>ROOK</b><span>PROFESSIONALLY OVERCONFIDENT</span></div><b id="health-text">100</b></div><div class="health-track"><i id="health-fill"></i></div><div class="player-status"><span id="status-text">READY FOR QUESTIONABLE DECISIONS</span><span id="mission-time">00:00</span></div></div>
      <div class="abilities"><div class="ability" id="dash-ability"><div class="ability-icon">↝</div><span class="key small">Q</span><b>ARCANE DASH</b><span class="cooldown" id="dash-time">READY</span></div><div class="ability" id="shock-ability"><div class="ability-icon">◎</div><span class="key small">E</span><b>SHOCKWAVE</b><span class="cooldown" id="shock-time">READY</span></div></div>
      <div class="weapon-card"><div class="weapon-label"><span class="eyebrow">EQUIPPED</span><b id="weapon-name">ARCANE BLASTER</b></div><div class="ammo-row"><span id="ammo">32</span><span class="ammo-divider">/</span><span id="reserve">320</span><span class="key small">R</span></div><div class="weapon-slots">${WEAPONS.map((w,i)=>`<span id="slot-${i}" class="${i===0?'selected':''}">${w.key}<i>${['✧','≋','◇','♧'][i]}</i></span>`).join('')}</div><div id="reload-progress" class="reload-progress hidden"><i></i><span>RELOADING</span></div></div>
      <div id="lock-hint" class="lock-hint">Click the game to control the camera <span class="key small">ESC</span> pauses</div><div id="kill-feed" class="kill-feed"></div><div id="quip" class="quip hidden"></div><div id="toast" class="toast hidden"></div><div id="combo" class="combo hidden"></div><div id="floating-numbers"></div>
    </section>
    <section id="pause" class="pause screen hidden"><div class="pause-card"><div class="eyebrow">A BRIEF STRATEGIC RETREAT</div><h2>Paused<span>.</span></h2><p>Even legends need a breather.</p><button id="resume" class="primary">RESUME ADVENTURE ${arrow}</button><button data-modal="settings" class="secondary">SETTINGS</button><button id="restart" class="secondary">RESTART MISSION</button><button id="pause-menu" class="text-button">RETURN TO MAIN MENU</button></div></section>
    <section id="result" class="result screen hidden"><div class="result-card"><div class="brand-gem">${emblem}</div><div class="eyebrow" id="result-eyebrow">VILLAGE STATUS: PROBABLY SAVED</div><h2 id="result-title">Mission complete<span>.</span></h2><p id="result-detail">The crystal is safe. Your reputation is debatable.</p><div id="result-stats" class="result-stats"></div><button id="retry" class="primary">PLAY AGAIN ${arrow}</button><button id="result-menu" class="text-button">MAIN MENU</button></div></section>
    <section id="modal" class="modal screen hidden"><div class="modal-panel"><button id="modal-close" class="modal-close" aria-label="Close panel">✕</button><div id="modal-content"></div></div></section>
    <section id="mobile" class="mobile-notice screen hidden"><div class="brand-gem">${emblem}</div><h2>This adventure needs<br>a keyboard & mouse.</h2><p>Open Chaos Legends on a desktop or laptop browser with WebGL 2. Your next questionable quest will be waiting.</p><a href="${GAME.repo}" target="_blank" rel="noopener" class="primary">VIEW THE PROJECT ${arrow}</a></section>`;
    this.refs=Object.fromEntries([...this.el.querySelectorAll('[id]')].map(e=>[e.id,e]));this.map=this.refs.minimap.getContext('2d');
  }
  bind(){this.refs.play.onclick=()=>this.game.start(false);this.refs.continue.onclick=()=>this.game.start(true);this.refs.resume.onclick=()=>this.game.resume();this.refs.restart.onclick=()=>this.game.start(false);this.refs['pause-menu'].onclick=()=>this.game.menu();this.refs.retry.onclick=()=>this.game.start(false);this.refs['result-menu'].onclick=()=>this.game.menu();this.refs['modal-close'].onclick=()=>this.closeModal();for(const button of this.el.querySelectorAll('[data-modal]'))button.onclick=()=>this.openModal(button.dataset.modal);}
  show(id,visible=true){this.refs[id].classList.toggle('hidden',!visible);}
  loading(done,total){const p=Math.round(done/total*100);this.refs['load-fill'].style.width=p+'%';this.refs['load-percent'].textContent=p+'%';this.refs['load-note'].textContent=p<60?'Loading the valley & village':p<95?'Preparing animated heroes & enemies':'Assembling your questionable adventure';}
  screen(state){for(const name of ['menu','hud','pause','result'])this.show(name,state===name||name==='hud'&&state==='playing');this.show('loading',false);if(state==='menu')this.refs.continue.disabled=!this.game.canContinue();if(state!=='playing')this.show('modal',false);}
  openModal(type){this.currentModal=type;this.game.audio.play('ui');this.show('modal');this.refs['modal-content'].innerHTML=type==='settings'?this.settingsHTML():type==='controls'?this.controlsHTML():this.aboutHTML();if(type==='settings')this.bindSettings();this.refs['modal-close'].focus();}
  closeModal(){this.show('modal',false);this.currentModal=null;}
  settingsHTML(){const s=this.game.settings;return `<div class="eyebrow">MAKE IT YOURS</div><h2>Settings<span>.</span></h2><p class="modal-intro">A little less chaos. A little more control.</p><div class="settings-grid"><div class="settings-group"><h3>VISUALS</h3><label class="setting">Graphics quality <select data-setting="quality">${['low','medium','high','ultra'].map(q=>`<option value="${q}" ${s.quality===q?'selected':''}>${q[0].toUpperCase()+q.slice(1)}</option>`).join('')}</select></label>${this.range('scale','Resolution scale',0.5,1.5,0.1,s.scale)}${['shadows','particles','post'].map(k=>`<label class="setting">${{shadows:'Dynamic shadows',particles:'Magic & particles',post:'Bloom & color grading'}[k]}<input type="checkbox" data-setting="${k}" ${s[k]?'checked':''}></label>`).join('')}</div><div class="settings-group"><h3>CONTROLS & AUDIO</h3>${this.range('sensitivity','Mouse sensitivity',0.2,2.5,0.1,s.sensitivity)}${this.range('master','Master volume',0,1,0.05,s.master)}${this.range('music','Music volume',0,1,0.05,s.music)}${this.range('sfx','Sound effects',0,1,0.05,s.sfx)}</div></div><p class="settings-note">Changes apply immediately and are saved on this device. Lower quality reduces shadow resolution and rendering cost.</p>`;}
  range(key,label,min,max,step,value){return `<label class="setting range-setting"><span>${label}<output id="setting-${key}">${value.toFixed(2)}</output></span><input type="range" min="${min}" max="${max}" step="${step}" value="${value}" data-setting="${key}"></label>`;}
  bindSettings(){for(const e of this.refs['modal-content'].querySelectorAll('[data-setting]'))e.oninput=()=>{const k=e.dataset.setting;this.game.settings[k]=e.type==='checkbox'?e.checked:e.tagName==='SELECT'?e.value:Number(e.value);const out=this.el.querySelector('#setting-'+k);if(out)out.textContent=Number(e.value).toFixed(2);if(k==='quality'){const presets={low:0.7,medium:0.85,high:1,ultra:1.2};this.game.settings.scale=presets[e.value];const scale=this.el.querySelector('[data-setting="scale"]');scale.value=this.game.settings.scale;this.el.querySelector('#setting-scale').textContent=this.game.settings.scale.toFixed(2);}this.game.applySettings();};}
  controlsHTML(){const controls=[['W A S D','Move with the camera'],['MOUSE','Orbit the shoulder camera'],['LEFT CLICK','Fire equipped weapon'],['RIGHT CLICK','Aim / tighten the crosshair'],['SHIFT','Sprint'],['SPACE','Jump / dodge boss shockwaves'],['C / CTRL','Crouch'],['R','Reload'],['1 · 2 · 3 · 4','Switch all four weapons'],['Q','Arcane dash · 4s cooldown'],['E','Shockwave · 9s cooldown'],['V','Melee strike'],['F','Open chest / recover crystal'],['ESC','Pause / release mouse']];return `<div class="eyebrow">A FIELD GUIDE FOR THE UNQUALIFIED</div><h2>Controls<span>.</span></h2><div class="controls-grid">${controls.map(([key,description])=>`<div><b class="control-key">${key}</b><span>${description}</span></div>`).join('')}</div><p class="settings-note">Click START, then click the game if your browser asks for mouse control. Keep moving, use cover, and reload between encounters. The boss shield glows purple; attack when it fades.</p>`;}
  aboutHTML(){return `<div class="eyebrow">ORIGINAL WORLD. QUESTIONABLE HERO.</div><h2>Chaos Legends<span>.</span></h2><p class="modal-intro">Rook, the valley's most confident and least qualified mercenary, arrives to rescue a village from goblins who seem very confused about the entire invasion.</p><div class="about-details"><div><h3>CREATED BY</h3><p>${GAME.author}<br>Azadi Studio</p></div><div><h3>BUILT WITH</h3><p>Three.js · WebGL 2 · Vite<br>JavaScript · Web Audio</p></div><div><h3>3D ASSET CREDITS</h3><p>Fantasy Town Kit by Kenney · CC0<br>RPG Characters & Animated Monsters by Quaternius · CC0<br>Original weapon, chicken, prop and level art.</p></div><div><h3>AUDIO & MUSIC</h3><p>Original synthesized effects and adaptive arcade music. No external recordings or commercial tracks.</p></div></div><a class="primary" href="${GAME.repo}" target="_blank" rel="noopener">SOURCE CODE & FULL CREDITS ${arrow}</a><p class="settings-note">Single-player desktop browser game. One complete mission. Progress and settings stay on this device.</p>`;}
  weaponChanged(w){this.refs['weapon-name'].textContent=w.short;for(let i=0;i<4;i++)this.refs['slot-'+i].classList.toggle('selected',WEAPONS[i]===w);}
  objective(stage,count){if(stage!==this.lastStage){this.lastStage=stage;const o=OBJECTIVES[stage];if(o){this.refs['objective-title'].textContent=o.title;this.refs['objective-detail'].textContent=o.detail;this.refs['objective-count'].textContent=String(stage+1).padStart(2,'0')+' / 07';this.el.querySelectorAll('[data-step]').forEach(e=>{e.classList.toggle('done',Number(e.dataset.step)<stage);e.classList.toggle('active',Number(e.dataset.step)===stage);});}}if(stage===1)this.refs['objective-detail'].textContent=`${count} invaders remaining · The square is definitely not theirs.`;}
  toast(text,duration=2.3){if(this.toastTimer>0&&this.refs.toast.textContent===text)return;this.refs.toast.textContent=text;this.toastTimer=duration;this.show('toast');}
  quip(text){if(this.quipTimer>1)return;this.refs.quip.textContent=text;this.quipTimer=4;this.show('quip');}
  hit(head=false){this.hitTimer=0.14;this.show('hitmarker');this.refs.hitmarker.classList.toggle('headshot',head);}
  damage(){this.refs.damage.classList.remove('active');void this.refs.damage.offsetWidth;this.refs.damage.classList.add('active');}
  kill(type,headshot){const names={grunt:'Goblin Grunt',archer:'Goblin Archer',orc:'Armored Orc',mushroom:'Exploding Mushroom',chicken:'Wizard Chicken',boss:'The Grand Gobbler'};const e=document.createElement('div');e.textContent=(headshot?'◇ ': '✧ ')+names[type];this.refs['kill-feed'].prepend(e);while(this.refs['kill-feed'].children.length>4)this.refs['kill-feed'].lastChild.remove();setTimeout(()=>e.remove(),3200);}
  floating(amount,pos,head){if(this.floaters.length>22)return;const e=document.createElement('span');e.className='damage-number'+(head?' gold':'');e.textContent=String(amount);this.refs['floating-numbers'].append(e);this.floaters.push({e,pos:pos.clone(),life:0.7,total:0.7});}
  update(dt){const g=this.game,p=g.player,w=g.combat,health=Math.ceil(p.health);this.refs['health-text'].textContent=health;this.refs['health-fill'].style.width=health+'%';this.refs['health-fill'].classList.toggle('low',health<30);this.refs.ammo.textContent=w.ammo[w.index].mag;this.refs.reserve.textContent=w.ammo[w.index].reserve;this.refs.score.textContent=String(g.stats.score).padStart(6,'0');this.refs.coins.textContent=p.coins+' ◈';this.refs['mission-time'].textContent=formatTime(g.mission.elapsed);this.refs['status-text'].textContent=p.shield>0?'ARCANE SHIELD · '+Math.ceil(p.shield)+'s':p.boost>0?'DOUBLE DAMAGE · '+Math.ceil(p.boost)+'s':'READY FOR QUESTIONABLE DECISIONS';
    this.refs['dash-time'].textContent=p.dash>0?p.dash.toFixed(1)+'s':'READY';this.refs['shock-time'].textContent=p.shock>0?p.shock.toFixed(1)+'s':'READY';this.refs['dash-ability'].classList.toggle('cooling',p.dash>0);this.refs['shock-ability'].classList.toggle('cooling',p.shock>0);
    this.refs.crosshair.classList.toggle('aiming',g.input.mouse.aim);this.show('reload-progress',w.reloadTimer>0);if(w.reloadTimer>0)this.refs['reload-progress'].querySelector('i').style.width=((1-w.reloadTimer/WEAPONS[w.index].reload)*100)+'%';this.show('lock-hint',!g.input.locked&&g.state==='playing');
    const interaction=g.world.interact(p);this.show('interaction',!!interaction);if(interaction)this.refs['interaction-text'].textContent=interaction.label;if(interaction&&g.input.once('KeyF'))interaction.action();
    const boss=g.enemies.boss;this.show('boss-hud',g.mission.stage===5&&boss?.alive);if(boss?.alive){this.refs['boss-fill'].style.width=Math.max(0,boss.hp/boss.maxHp*100)+'%';this.refs['boss-state'].textContent=boss.shield?'SHIELD ACTIVE':'SHIELD DOWN · ATTACK';}
    const point=g.mission.marker.position.clone().project(g.renderer.camera);this.show('objective-marker',g.mission.stage<7&&point.z<1);this.refs['objective-marker'].style.left=clamp((point.x*.5+.5)*innerWidth,40,innerWidth-40)+'px';this.refs['objective-marker'].style.top=clamp((-point.y*.5+.5)*innerHeight,165,innerHeight-175)+'px';this.refs['marker-distance'].textContent=Math.ceil(g.mission.marker.position.distanceTo(p.pos))+' m';
    this.refs.heading.textContent=['N','NE','E','SE','S','SW','W','NW'][((Math.round(-g.camera.yaw/(Math.PI/4))%8)+8)%8];this.minimap();
    this.toastTimer=Math.max(0,this.toastTimer-dt);this.quipTimer=Math.max(0,this.quipTimer-dt);this.hitTimer=Math.max(0,this.hitTimer-dt);if(this.toastTimer===0)this.show('toast',false);if(this.quipTimer===0)this.show('quip',false);if(this.hitTimer===0)this.show('hitmarker',false);
    this.show('combo',g.combo>1&&g.comboTime>0);if(g.combo>1)this.refs.combo.textContent=`${g.combo} × COMBO`;
    for(let i=this.floaters.length-1;i>=0;i--){const f=this.floaters[i];f.life-=dt;const point=f.pos.clone().add(new THREE.Vector3(0,(1-f.life/f.total)*0.8,0)).project(g.renderer.camera);f.e.style.transform=`translate(${(point.x*.5+.5)*innerWidth}px,${(-point.y*.5+.5)*innerHeight}px)`;f.e.style.opacity=Math.max(0,f.life/f.total);if(f.life<=0||point.z>1){f.e.remove();this.floaters.splice(i,1);}}
  }
  minimap(){const g=this.game,p=g.player,ctx=this.map;ctx.clearRect(0,0,192,166);ctx.fillStyle='#839c8630';ctx.fillRect(12,8,168,145);const project=(x,z)=>[96+x*2.5,139+(z-p.pos.z)*2.0];ctx.strokeStyle='#d4d3af35';ctx.lineWidth=10;ctx.beginPath();ctx.moveTo(96,0);ctx.lineTo(96,166);ctx.stroke();const river=project(0,-58);ctx.fillStyle='#78c8c16b';ctx.fillRect(12,river[1]-9,168,19);ctx.fillStyle='#b8a37a';ctx.fillRect(89,river[1]-11,14,24);for(const e of g.enemies.enemies){if(!e.alive||e.pos.distanceTo(p.pos)>35)continue;const [x,y]=project(e.pos.x,e.pos.z);if(y<8||y>153)continue;ctx.fillStyle=e.type==='boss'?'#edd69c':'#e5a98f';ctx.beginPath();ctx.arc(x,y,e.type==='boss'?4:2.5,0,Math.PI*2);ctx.fill();}const o=OBJECTIVES[g.mission.stage];if(o){const [x,y]=project(o.pos[0],o.pos[2]);ctx.strokeStyle='#f7df9f';ctx.lineWidth=1.8;ctx.strokeRect(x-3,clamp(y,14,150)-3,6,6);}ctx.save();ctx.translate(96,139);ctx.rotate(-g.camera.yaw);ctx.fillStyle='#b5f0d4';ctx.beginPath();ctx.moveTo(0,-6);ctx.lineTo(4,4);ctx.lineTo(0,2);ctx.lineTo(-4,4);ctx.closePath();ctx.fill();ctx.restore();}
  result(win){this.screen('result');this.refs['result-eyebrow'].textContent=win?'VILLAGE STATUS: PROBABLY SAVED':'HERO STATUS: TEMPORARILY UNAVAILABLE';this.refs['result-title'].textContent=win?'Mission complete.':'A tactical defeat.';this.refs['result-detail'].textContent=win?'The crystal is safe. Your reputation is debatable.':'Your plan was bold. Perhaps excessively bold. Try again.';this.refs.retry.textContent=win?'PLAY AGAIN →':'RETRY MISSION →';const g=this.game,s=g.stats;const stats=[['SCORE',s.score.toLocaleString()],['ENEMIES DEFEATED',s.kills],['ACCURACY',s.shots?Math.min(100,Math.round(s.hits/s.shots*100))+'%':'—'],['COLLECTIBLES',s.collectibles],['MISSION TIME',formatTime(g.mission.elapsed)],['BEST SCORE',g.best.toLocaleString()]];this.refs['result-stats'].innerHTML=stats.map(([label,v])=>`<div><span>${label}</span><b>${v}</b></div>`).join('');}
  fatal(message){this.screen('menu');this.show('menu',false);this.show('modal');this.refs['modal-close'].classList.add('hidden');this.refs['modal-content'].innerHTML=`<div class="eyebrow">ADVENTURE INTERRUPTED</div><h2>Let's try again.</h2><p>${message}</p><button class="primary" onclick="location.reload()">RELOAD GAME →</button>`;}
}
