import * as THREE from 'three';
export const bone=(model,name)=>model.getObjectByName(name)||model.getObjectByName(name.replaceAll('.',''));
export function playerClips(model,source){const clips=[...source],idle=source.find(c=>c.name==='Idle');
  for(const [name,from] of [['Aim','Idle_Weapon'],['Shoot','Bow_Shoot'],['Reload','PickUp'],['Melee','Punch']]){const c=source.find(c=>c.name===from);if(c){const clone=c.clone();clone.name=name;clips.push(clone);}}
  function pose(name,amount,duration){const tracks=idle?idle.clone().tracks:[];for(const [joint,bend] of [['UpperLeg.L',-.6],['UpperLeg.R',-.4],['LowerLeg.L',.7],['LowerLeg.R',.55]]){const b=bone(model,joint);if(!b)continue;const trackName=b.name+'.quaternion';const native=idle?.tracks.find(t=>t.name===trackName);const rest=native?new THREE.Quaternion().fromArray(native.values):b.quaternion.clone();const end=rest.clone().multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1,0,0),bend*amount));const i=tracks.findIndex(t=>t.name===trackName);if(i>=0)tracks.splice(i,1);tracks.push(new THREE.QuaternionKeyframeTrack(trackName,[0,duration*.32,duration],[...rest.toArray(),...end.toArray(),...end.toArray()]));}clips.push(new THREE.AnimationClip(name,duration,tracks));}
  pose('Jump',1,0.4);pose('Fall',0.4,0.5);pose('Land',0.22,0.18);return clips;
}
export function poseArms(player){const g=player.game;if(player.meleeTimer>0||g.combat?.reloadTimer>0)return;player.root.updateWorldMatrix(true,true);
  for(const side of ['R','L']){const upper=bone(player.model,'UpperArm.'+side),lower=bone(player.model,'LowerArm.'+side),wrist=bone(player.model,'Fist.'+side);if(!upper||!lower||!wrist)continue;const target=player.weaponRig.localToWorld(new THREE.Vector3(0,side==='R'?-.22:-.05,side==='R'?-.07:.31));const s=upper.getWorldPosition(new THREE.Vector3()),scale=upper.getWorldScale(new THREE.Vector3()).y,l1=lower.position.length()*scale,l2=wrist.position.length()*scale;const direction=target.clone().sub(s),distance=Math.min(direction.length(),l1+l2-.01);direction.normalize();const along=(l1*l1-l2*l2+distance*distance)/(2*Math.max(distance,.01)),height=Math.sqrt(Math.max(0,l1*l1-along*along));const bend=new THREE.Vector3(side==='R'?.65:-.5,-1,0).applyQuaternion(player.root.quaternion);bend.addScaledVector(direction,-bend.dot(direction)).normalize();const elbow=s.clone().addScaledVector(direction,along).addScaledVector(bend,height);
    const parentQ=upper.parent.getWorldQuaternion(new THREE.Quaternion()).invert(),upperDir=elbow.clone().sub(s).normalize().applyQuaternion(parentQ);upper.quaternion.setFromUnitVectors(lower.position.clone().normalize(),upperDir);upper.updateWorldMatrix(false,true);const elbowNow=lower.getWorldPosition(new THREE.Vector3()),lowerDir=target.clone().sub(elbowNow).normalize().applyQuaternion(lower.parent.getWorldQuaternion(new THREE.Quaternion()).invert());lower.quaternion.setFromUnitVectors(wrist.position.clone().normalize(),lowerDir);lower.updateWorldMatrix(false,true);
  }
}
