import * as THREE from 'three';
export class Particles {
  constructor(scene,settings){this.settings=settings;this.max=900;this.data=Array.from({length:this.max},()=>({life:0,total:1,vx:0,vy:0,vz:0}));this.positions=new Float32Array(this.max*3);this.colors=new Float32Array(this.max*3);this.positions.fill(-10000);const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(this.positions,3));geo.setAttribute('color',new THREE.BufferAttribute(this.colors,3));const c=document.createElement('canvas');c.width=c.height=32;const ctx=c.getContext('2d'),g=ctx.createRadialGradient(16,16,0,16,16,16);g.addColorStop(0,'#ffffff');g.addColorStop(0.3,'#fff');g.addColorStop(1,'#ffffff00');ctx.fillStyle=g;ctx.fillRect(0,0,32,32);const tex=new THREE.CanvasTexture(c);this.points=new THREE.Points(geo,new THREE.PointsMaterial({size:0.18,map:tex,vertexColors:true,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending}));this.points.frustumCulled=false;scene.add(this.points);this.cursor=0;this.rings=[];this.scene=scene;this.color=new THREE.Color();}
  burst(pos,color=0xffc878,count=16,speed=4,life=0.5){if(!this.settings.particles)return;const cap=this.settings.quality==='low'?Math.min(count,8):count;this.color.setHex(color);for(let n=0;n<cap;n++){const i=this.cursor++%this.max,p=this.data[i];p.life=life*(0.5+Math.random()*0.5);p.total=p.life;p.vx=(Math.random()-0.5)*speed;p.vy=Math.random()*speed*0.8;p.vz=(Math.random()-0.5)*speed;this.positions[i*3]=pos.x;this.positions[i*3+1]=pos.y;this.positions[i*3+2]=pos.z;this.colors[i*3]=this.color.r;this.colors[i*3+1]=this.color.g;this.colors[i*3+2]=this.color.b;}}
  ring(pos,color=0x85f4c3,radius=7,life=0.6){const mesh=new THREE.Mesh(new THREE.TorusGeometry(1,0.028,5,48),new THREE.MeshBasicMaterial({color,transparent:true,opacity:0.8,depthWrite:false}));mesh.rotation.x=-Math.PI/2;mesh.position.copy(pos);mesh.position.y+=0.12;this.scene.add(mesh);this.rings.push({mesh,radius,life,total:life});}
  update(dt){for(let i=0;i<this.max;i++){const p=this.data[i];if(p.life<=0)continue;p.life-=dt;if(p.life<=0){this.positions[i*3+1]=-10000;continue;}this.positions[i*3]+=p.vx*dt;this.positions[i*3+1]+=p.vy*dt;this.positions[i*3+2]+=p.vz*dt;p.vy-=4*dt;}
    this.points.geometry.attributes.position.needsUpdate=true;this.points.geometry.attributes.color.needsUpdate=true;
    for(let i=this.rings.length-1;i>=0;i--){const r=this.rings[i];r.life-=dt;const t=1-r.life/r.total;r.mesh.scale.setScalar(0.2+t*r.radius);r.mesh.material.opacity=0.8*(1-t);if(r.life<=0){this.scene.remove(r.mesh);r.mesh.geometry.dispose();r.mesh.material.dispose();this.rings.splice(i,1);}}
  }
  clear(){for(const p of this.data)p.life=0;this.positions.fill(-10000);for(const r of this.rings){this.scene.remove(r.mesh);r.mesh.geometry.dispose();r.mesh.material.dispose();}this.rings=[];}
}
